# Generated by Django 5.0.1 on 2024-02-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherrequest',
            name='approved_as_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
