# Generated by Django 5.0.1 on 2024-02-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_teacherrequest_current_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='fullName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
