# Generated by Django 5.0.1 on 2024-02-09 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_teachermodel_fullname_teachermodel_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_as_teacher', models.BooleanField(default=False)),
                ('fullName', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number: ')),
                ('current_location', models.TextField(blank=True, choices=[('in_dhaka', 'Inside Dhaka'), ('in_gazipur', 'Inside Gazipur'), ('others', 'Others')], null=True, verbose_name='Current Location')),
                ('current_address', models.TextField(blank=True, null=True)),
                ('university_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='University')),
                ('department', models.CharField(blank=True, max_length=50, null=True, verbose_name='Department')),
                ('current_education_year', models.CharField(blank=True, choices=[('1st_year', '1st Year'), ('2nd_year', '2nd Year'), ('3rd_year', '3rd Year'), ('4th_year', '4th Year'), ('graduated', 'Graduated'), ('post_graduation_running', 'Enrolled In Postgraduation studies')], max_length=50, null=True, verbose_name='Current Education Year:')),
                ('fb_link', models.CharField(blank=True, max_length=300, null=True, verbose_name='Facebook Link')),
                ('interested_teaching_area', models.CharField(blank=True, choices=[('polytechnic', 'Polytechnic'), ('class_6_to_12', 'Class 6-12'), ('duet_admission', 'DUET Admission')], max_length=50, null=True, verbose_name='Interested Teaching Segments')),
                ('interested_subjects', models.CharField(blank=True, choices=[('non_department', 'Non Department'), ('department', 'Department')], max_length=50, null=True, verbose_name='Interested Subjects')),
                ('link_previous_class', models.CharField(blank=True, max_length=200, null=True, verbose_name='Previous Class Link Live or Recorded')),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('describe_your_experience', models.TextField(blank=True, null=True)),
                ('cv', models.FileField(blank=True, max_length=150, null=True, upload_to='teacher_cv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='TeacherRequest',
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(to='account.teacher'),
        ),
        migrations.DeleteModel(
            name='TeacherModel',
        ),
    ]
