# Generated by Django 5.0.1 on 2024-02-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_teacher_remove_teachermodel_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Phone Number: '),
        ),
    ]
