# Generated by Django 5.0.1 on 2024-02-09 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_coursecategory_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecategory',
            old_name='course_category',
            new_name='name',
        ),
    ]
